site_name: Open-Source-Advisor
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            show_root_heading: true
            show_object_full_path: false

nav:
  - User Guide:
    - index.md
  - API Reference:
      - Github Agent: core/github_agent/github_agent.md
      - Model Handler: core/models/models.md
      - OSA Tree Sitter:
          - core/osatreesitter/osatreesitter.md
          - Documentation Generator: core/osatreesitter/docgen.md

repo_url: https://github.com/aimclub/OSA

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aimclub/OSA

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: True
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences